apiVersion: v1
kind: Pod
metadata:
  name: unsecure
  annotations:
    ignore-check.kube-linter.io/run-as-non-root: "Ce pod interagit avec le système. Il a besoin d’être root."
spec:
  containers:
  - name: demo
    image: busybox
    resources:
      requests:
        memory: "8Gi"
        cpu: "250m"
    command: [ "sh", "-c", "sleep 1h" ]
