apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: kubelinter-sample
  namespace: kubelinter
spec:
  type: git
  params:
  - name: revision
    value: main
  - name: url
    value: https://github.com/nmasse-itix/programmez-kubelinter.git
