apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubelinter
  namespace: kubelinter
spec:
  resources:
    inputs:
    - name: src
      type: git
  steps:
  - name: kubelinter
    image: stackrox/kube-linter:0.2.3-alpine
    workingDir: /workspace/src
    command: [ "/kube-linter", "lint", "./kube" ]
